### ISSUE TITLE
About wgan part

### ISSUE THREAD

**Issue by QierMeng123** [jacons/MeRGAN-V2#1]
Hi, Im studying this code. However, I didn't find the wgan part described in the paper. Did you implement it?

**Comment by jacons** [comment]
Hi! 
Thank you for your question. I've developed this project for a Continual Learning course (Master degree course at Pisa University). In the my assignment was not required use the method for all datasets proposed in the original paper. I've worked only with the MNIST dataset (the easiest one). Since the images were not so much complicated, it was enough  to implement the classical acGAN without the Wasserstein distance. However, I link you an example of this variety.

https://github.com/Lornatang/WassersteinGAN_GP-PyTorch/blob/master/wgangp_pytorch/models.py

Jacons
